export const COLOR_EXTENSION_MAP : {[key: string]: string;} = {
    pdf: "red",
    doc: "blue",
    docx: "blue",
    xls: "green",
    xlsx: "green",
    ppt: "orange",
    pptx: "orange",
    jpg: "yellow",
    jpeg: "yellow",
    png: "yellow",
    gif: "yellow",
    svg: "yellow",
    mp3: "purple",
    mp4: "purple",
    mov: "purple",
    avi: "purple",
    txt: "gray",
    zip: "gray",
    rar: "gray",
    json: "gray",
    xml: "gray",
    html: "gray",

}